# Generated by Django 5.0.1 on 2024-02-06 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookorder',
            options={'ordering': ['-create_time', 'price']},
        ),
    ]
