# Generated by Django 5.0.1 on 2024-02-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
