# Generated by Django 5.0.1 on 2024-02-02 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
        ('frontuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontuser.frontuser'),
        ),
    ]
