# Generated by Django 5.0.1 on 2024-02-02 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_authot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='authot',
            new_name='author',
        ),
    ]
