# Generated by Django 5.0.1 on 2024-02-02 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_rename_authot_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('originComment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.comment')),
            ],
        ),
    ]
